Re-factor injector_test.go
cyberstudio/jsonj pull request #3
Opened 2024-02-02 21:04 UTC by mcei

Отрефакторил `injector_test.go`, чтобы отвязаться от зависимости `github.com/stretchr/testify`, поскольку она прилично раздувает [go.mod](https://github.com/cyberstudio/jsonj/blob/cf21e03f28030d576be4b88c0138331d4b7743ce/go.mod) и [go.sum](https://github.com/cyberstudio/jsonj/blob/cf21e03f28030d576be4b88c0138331d4b7743ce/go.sum)

2024-02-05 05:03 UTC, neexee approved these changes

2024-02-05 08:12 UTC, sda0 requested changes

2024-02-05 08:12 UTC, sda0 commented on injector_test.go
> +				requireNoError(t, err)
на этой строчке выполнение не прекратится, поэтому это не `require...`

2024-02-05 08:12 UTC, sda0 commented on injector_test.go
> +}
такие двустрочные функи всегда заставляются задумать о их необходимости.
предлагаю лучше заинлайнить - так ты обеспечишь и выход из теста если пришла ошибка, и избавишься от этой недофункции

2024-02-05 18:22 UTC, mcei commented on injector_test.go
> +				requireNoError(t, err)
Понял

2024-02-05 18:22 UTC, mcei commented on injector_test.go
> +}
Сделал

2024-02-05 18:28 UTC, sda0 requested changes

2024-02-05 18:28 UTC, sda0 commented on injector_test.go
> +					t.Errorf(err.Error())
```suggestion
					t.Error(err)
					return
```

2024-02-05 22:04 UTC, mcei commented on injector_test.go
> +					t.Errorf(err.Error())
Спасибо. Сделал.

2024-02-06 06:52 UTC, sda0 requested changes

2024-02-06 06:52 UTC, sda0 commented on injector_test.go
> +func assertJSONEqual(t *testing.T, expected, actual string) {
извини, вовремя не заметил, эта функа, по сути, хелпер ассерта.  принято их так и помечать чтобы сообщение об ошибке на нужную строчку в коде указывало:
```suggestion
func assertJSONEqual(t *testing.T, expected, actual string) {
    t.Helper()
```

2024-02-06 06:52 UTC, sda0 commented on injector_test.go
> +					t.Error(err)
слушай, извини, утро вечера мудренее, пару `t.Error` + `return` можно заменить на `t.Fatal`
```suggestion
					t.Fatal(err)
```

2024-02-06 06:52 UTC, sda0 commented on injector_test.go
> +		t.Errorf("Expected ('%s') is not a valid json: '%s'", expected, err.Error())
это не ошибка теста, это ошибка его составления, поэтому тут паника, но не крит если оставишь t.Fatal

и я бы точно убрал вывод actual / expected из этой ошибки - они зачастую очень большие и лишь затруднят разбор

```suggestion
		panic("expected value is not a valid json: " + err.Error())
```

2024-02-06 06:52 UTC, sda0 commented on injector_test.go
> +		t.Errorf("Actual ('%s') is not a valid json: '%s'", actual, err.Error())
- `Fatalf`
- `err` в аргументах не нуждается в вызове `Error()`
- ```suggestion
		t.Fatalf("Actual is not a valid json: '%s'", err)
```
и ниже лишняя строка

2024-02-06 06:52 UTC, sda0 commented on injector_test.go
> +		t.Errorf("Not equal:\n  expected: %s\n  actual: %s", expectedJSON, actualJSON)
```suggestion
		t.Errorf("Not equal:\n  expected: %s\n  actual: %s", expectedJSON, actualJSON)
```

2024-02-06 09:52 UTC, mcei commented on injector_test.go
> +					t.Error(err)
Отлично!

2024-02-06 18:29 UTC, mcei commented on injector_test.go
> +func assertJSONEqual(t *testing.T, expected, actual string) {
Сделал

2024-02-06 18:30 UTC, mcei commented on injector_test.go
> +					t.Error(err)
Сделал

2024-02-06 18:30 UTC, mcei commented on injector_test.go
> +		t.Errorf("Actual ('%s') is not a valid json: '%s'", actual, err.Error())
Готово

2024-02-06 18:30 UTC, mcei commented on injector_test.go
> +		t.Errorf("Expected ('%s') is not a valid json: '%s'", expected, err.Error())
Супер

2024-02-06 18:36 UTC, sda0 approved these changes

2024-02-06 19:49 UTC, merged